---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: |
  https://io.adafruit.com/api/v2/{{ adafruit_username }}/feeds/{{ adafruit_feed_id }}
  https://io.adafruit.com/api/v2/{{ adafruit_username }}/feeds/{{ adafruit_feed_id }}/data/chart?hours={{ adafruit_lookback | default: 1 }}&field={{ adafruit_aggregate }}&resolution={{ adafruit_resolution }}
polling_headers: X-AIO-Key={{ adafruit_api_key }}
polling_body: 
id: 112643
custom_fields:
- keyname: author_bio
  name: About This Plugin
  field_type: author_bio
  description: Show data collected via Adafruit IO
  github_url: https://github.com/stephenyeargin/trmnl-adafruit-io
  learn_more_url: https://io.adafruit.com/
  email_address: stephen@yearg.in
- keyname: adafruit_username
  field_type: string
  name: Adafruit IO Username
  description: Your username for Adafruit IO
  placeholder: ladyada
- keyname: adafruit_api_key
  field_type: password
  name: Adafruit IO API Key
  description: API Key obtained through the Adafruit IO UI by clicking the Key icon
  placeholder: abcdef1234567890
- keyname: adafruit_feed_id
  field_type: string
  name: Feed ID
  description: The ID (not the name) of the feed receiving data.
  placeholder: my-device-feed
- keyname: adafruit_aggregate
  field_type: select
  name: Data Aggregation
  default: val
  options:
  - Value (default): val
  - Average: avg
  - Sum: sum
  - Minimum: min
  - Maximum: max
  - Value Count: val_count
- keyname: adafruit_resolution
  field_type: select
  name: Data Resolution (Minutes)
  default: 1
  options:
  - 1
  - 5
  - 10
  - 30
  - 60
  - 120
  - 240
  - 480
  - 960
- keyname: adafruit_lookback
  field_type: number
  name: Hours of Data
  description: The number of hours to return
  default: 24
  placeholder: 1
name: Adafruit IO
refresh_interval: 15
